# git-cliff ~ configuration file
# https://git-cliff.org/docs/configuration
[repo]
url = "drewbernetes"
repo = "container-security-action"
# Set the GITHUB_TOKEN env var with your PAT in to have this work. Fopr ease, set it in your ~/.bashrc, ~/.zshrc etc

[bump]
features_always_bump_minor = true
breaking_always_bump_major = true
initial_tag = "0.1.0"

[changelog]
# template for the changelog header
header = """
# Changelog\n
All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).\n
"""
# template for the changelog body
# https://keats.github.io/tera/docs/#introduction
body = """
{%- macro remote_url() -%}
  https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}
{%- endmacro -%}

{% if version -%}
    ## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else -%}
    ## [Unreleased]
{% endif -%}

{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | upper_first }}
    {%- for commit in commits | unique(attribute="message") %}
        - {{ commit.message | split(pat="\n") | first | upper_first | trim }}\
            {% if commit.remote.username %} by @{{ commit.remote.username }}{%- endif -%}
            {% if commit.remote.pr_number %} in \
            [#{{ commit.remote.pr_number }}]({{ self::remote_url() }}/pull/{{ commit.remote.pr_number }}) \
            {%- endif -%}
    {% endfor %}
{% endfor %}

{%- if github.contributors | filter(attribute="is_first_time", value=true) | length != 0 %}
  ## New Contributors
{%- endif -%}

{% for contributor in github.contributors | filter(attribute="is_first_time", value=true) %}
  * @{{ contributor.username }} made their first contribution
    {%- if contributor.pr_number %} in \
      [#{{ contributor.pr_number }}]({{ self::remote_url() }}/pull/{{ contributor.pr_number }}) \
    {%- endif %}
{%- endfor %}\n
"""
# template for the changelog footer
footer = """
{%- macro remote_url() -%}
  https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}
{%- endmacro -%}

{% for release in releases -%}
    {% if release.version -%}
        {% if release.previous.version -%}
            [{{ release.version | trim_start_matches(pat="v") }}]: \
                {{ self::remote_url() }}/compare/{{ release.previous.version }}..{{ release.version }}
        {% endif -%}
    {% else -%}
        [unreleased]: {{ self::remote_url() }}/compare/{{ release.previous.version }}..HEAD
    {% endif -%}
{% endfor %}
<!-- generated by git-cliff -->
"""
# remove the leading and trailing whitespace from the templates
trim = true

[git]
# parse the commits based on https://www.conventionalcommits.org
conventional_commits = true
# filter out the commits that are not conventional
filter_unconventional = false
# regex for preprocessing the commit messages
commit_preprocessors = [
    # remove issue numbers from commits
    { pattern = '\((\w+\s)?#([0-9]+)\)', replace = "" },
]
# regex for parsing and grouping commits
commit_parsers = [
    { message = "^[f|F]eat!", group = ":boom: Breaking Changes" },
    { message = "^[f|F]ix!", group = ":boom: Breaking Changes" },
    { message = "^[d|D]ocs!", group = ":boom: Breaking Changes" },
    { message = "^.*!", group = ":boom: Breaking Changes" },
    { message = "BREAKING CHANGE", group = ":boom: Breaking Changes" },
    { message = "^[f|F]eat", group = ":rocket: Added" },
    { message = "^[f|F]eature", group = ":rocket: Added" },
    { message = "^[f|F]ix", group = ":bug: Fixed" },
    { message = "^[d|D]ocs", group = ":books: Documentation" },
    { message = "^[s|S]tyle", group = ":art: Styling" },
    { message = "^[r|R]efactor", group = ":gear: Changed" },
    { message = "^[p|P]erf", group = ":zap: Performance" },
    { message = "^[t|T]est", group = ":test_tube: Testing" },
    { message = "^[c|C]hore", group = ":broom: Chore" },
    { message = "^[b|B]uild", group = ":package: Build" },
    { message = "^[c|C]i", group = ":construction_worker: CI" },
    { message = "^[r|R]evert", group = ":rewind: Reverted" },
    { message = "^.*", group = ":gear: Changed" },
]
# filter out the commits that are not matched by commit parsers
filter_commits = false
# sort the tags topologically
topo_order = false
# sort the commits inside sections by oldest/newest order
sort_commits = "newest"
# Ignore the dev tag
skip_tags = "dev"
ignore_tags = "dev"
